before_script:
  - npm list -g cordova || npm install -g cordova
  - npm list -g ios-deploy || npm install -g ios-deploy --unsafe-perm=true
script:
  - cordova build
  - set -o pipefail && xcodebuild build -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" -destination "$XCODE_DESNITATION" -derivedDataPath DerivedData -parallel-testing-enabled NO | xcpretty -f `xcpretty-travis-formatter`
  - cordova build --device
  - cordova build --device --release
git:
  depth: 1
install: skip
cache: npm
language: swift
osx_image: xcode10.1
xcode_scheme: HelloCordova
xcode_workspace: platforms/ios/HelloCordova.xcworkspace
